name: Social Media post

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed
  workflow_dispatch: # Run workflow manually if needed

jobs:
  linkedin:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Expose git commit data
      uses: jcputney/git-commit-data-action@v2
    
    - name: Get Latest Post / Post On Linkedin
      uses: Arisamiga/Linkedin-RSS@master
      if: "!contains(env.GIT_COMMIT_MESSAGE, 'NO CI')"
      with:
        feed_list: 'https://mattvsts.github.io/feed.xml'
        ln_access_token: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        embed_image: 'https://mattvsts.github.io/images/cover/iac.png'

  twitter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Expose git commit data
      uses: jcputney/git-commit-data-action@v2

    - uses: nearform-actions/github-action-notify-twitter@master
      if: "!contains(env.GIT_COMMIT_MESSAGE, 'NO CI')"
      with:
        message: |
          Blogged! ${{ env.GIT_COMMIT_MESSAGE }} - https://mattvsts.github.io #MVPBuzz #AzureDevOps #GitHub
        twitter-app-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
        twitter-app-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
        twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}