name: Social Media post

on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed
  workflow_dispatch: # Run workflow manually if needed

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'NO CI')"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Latest Post / Post On Linkedin
      uses: Arisamiga/Linkedin-RSS@master
      with:
        feed_list: 'https://mattvsts.github.io/feed.xml'
        ln_access_token: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        embed_image: 'https://mattvsts.github.io/images/cover/iac.png'
