name: Social Media post

# Controls when the action will run. Triggers the workflow on successful publishing of the pages.
on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed
  workflow_dispatch: # Run workflow manually if needed


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: "!contains(github.event.head_commit.message, 'NO CI')"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Get Latest Post / Post On Linkedin
      uses: Arisamiga/Linkedin-RSS@master
      with:
        feed_list: 'https://mattvsts.github.io/feed.xml'
        ln_access_token: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
        embed_image: # Url of embed image
