name: Twitter test

# Controls when the action will run. Triggers the workflow on successful publishing of the pages.
on:
  workflow_dispatch: # Run workflow manually if needed

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: nearform-actions/github-action-notify-twitter@master
        with:
          message: 'Testing a GitHub Actions workflow - ${{ github.event.workflow_run.head_commit.message }}'
          twitter-app-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          twitter-app-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          twitter-access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          twitter-access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}